

test:
	why3 patience.mlw --exec Patience.test

prove:
	why3ide patience.mlw

prove_state:
	why3ide patience_state.mlw

replay:
	why3replayer patience.mlw

replay_state:
	why3replayer patience_state.mlw

doc:
	why3doc patience.mlw

dump:
	why3session html patience.mlw
