

test:
	why3 patience.mlw --exec PatienceCode.test

prove:
	why3ide patience.mlw

replay:
	why3replayer patience.mlw

doc:
	why3 doc patience.mlw
	echo "HTML doc generated in file patience.html"

dump:
	why3session html patience.mlw
	echo "HTML session dump generated in file patience/why3session.html"
